apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paseo-workspace
  namespace: paseo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
